// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cronologia struct {
	ID          string        `json:"id"`
	Paciente    *Paciente     `json:"paciente"`
	Incidencias []*Incidencia `json:"incidencias"`
}

type Incidencia struct {
	ID          string `json:"id"`
	Tipo        string `json:"tipo"`
	Fecha       string `json:"fecha"`
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
}

type Paciente struct {
	Cedula          string `json:"cedula"`
	Nombre          string `json:"nombre"`
	FechaCumpleanos string `json:"fechaCumpleanos"`
}
