version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "apiHistoriaClinica"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ul0wm7ywphn7"
s3_prefix = "apiHistoriaClinica"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
